contact_links:
  - name: Discord
    about: Hedystia Discord
    url: https://hedystia.com/support
  - name: BoxMineWorld
    about: Free/Paid Hosting
    url: https://boxmineworld.com
  - name: BoxMineWorld Discord
    about: Free/Paid Hosting Discord
    url: https://discord.gg/84qsr4v
